version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "jda*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
